apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ejemplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: calderonperaza/ejemplobackend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/ejemplo
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: ejemplo
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort