apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  namespace: ejemplo
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: calderonperaza/ejemplofrontend:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: ejemplo
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
  namespace: ejemplo
spec:
  rules:
  - host: frontend.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80